[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{access = "read-write", path = "./"}]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "murky/=lib/murky/",
    "foundry-devops/=lib/foundry-devops/"
]
